AllCops:
  TargetRubyVersion: 2.3

  Exclude:
    - 'config/initializers/*'
    - 'db/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
