language: ruby
rvm:
  - 2.4.0
before_script:
  - bundle exec rake db:setup
bundler_args: '--without development production'
services:
  - elasticsearch
before_install:
  - gem update --system
  - gem --version
