default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mundodastrevas_development

test: &test
  <<: *default
  database: mundodastrevas_test

production:
  adapter: postgresql
  encoding: unicode
  database: mundodastrevas_production
  pool: 3
  username: mundodastrevas
  password: mundodastrevas
  host: localhost
  port: 5432

cucumber:
  <<: *test
