development:
  secret_key_base: '78375cae3aa8e30cb8fce028f8faffb93d5d73214b16248b7f222f7fc37203ee0c7799193e7f79b61614b3a467eb41a213b0cc6a869a3d6acf8dfb753eb9ad2e'
  recaptcha_public_key: '6LeUO9kSAAAAAEKT0aVgyTbbV3K2BJfW7ipaBy3o'
  recaptcha_private_key: '6LeUO9kSAAAAAALffASWtbFmk_nRbCbHr9gTGEMD'

test:
  secret_key_base: '78375cae3aa8e30cb8fce028f8faffb93d5d73214b16248b7f222f7fc37203ee0c7799193e7f79b61614b3a467eb41a213b0cc6a869a3d6acf8dfb753eb9ad2e'
  recaptcha_public_key: '6LeUO9kSAAAAAEKT0aVgyTbbV3K2BJfW7ipaBy3o'
  recaptcha_private_key: '6LeUO9kSAAAAAALffASWtbFmk_nRbCbHr9gTGEMD'

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  recaptcha_public_key: <%= ENV['RECAPTCHA_PUBLIC_KEY'] %>
  recaptcha_private_key: <%= ENV['RECAPTCHA_PRIVATE_KEY'] %>
  bugsnag_api_key: <%= ENV['BUGSNAG_API_KEY'] %>
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
